Feature/leaflet map
demostat/demostat pull request #61
Opened 2019-03-21 12:24 UTC by clerie

2019-03-21 20:01 UTC, frommMoritz requested changes

2019-03-21 20:01 UTC, frommMoritz commented on demostat/templates/demostat/demo_detail.html
> +  let mymap = L.map('mapid').setView([{{ demo.location.marker_lat }}, {{ demo.location.marker_lon }}], 13);
Die Karte ist für meinen Geschmack etwas weit hinausge-zoomt. Wenn wir einen überblickt in der Stadt geben wollen aber trotzdem noch Details auf der Karte zeigen wollen, wäre eine Zoom-Stufe von 15/16 angemessen.

2019-03-21 20:01 UTC, frommMoritz commented on demostat/templates/demostat/demo_detail.html
> +      <div id="mapid" class="embed-responsive-item"></div>
Dieser Name ist nicht sonderlich Aussagekräftig.
```suggestion
      <div id="location-map" class="embed-responsive-item"></div>
```

2019-03-21 20:01 UTC, frommMoritz commented on demostat/templates/demostat/demo_detail.html
> +  let mymap = L.map('mapid').setView([{{ demo.location.marker_lat }}, {{ demo.location.marker_lon }}], 13);
```suggestion
  let mymap = L.map('location-map').setView([{{ demo.location.marker_lat }}, {{ demo.location.marker_lon }}], 13);
```

2019-03-21 20:32 UTC, clerie commented
Die Doku fehlt auch noch

2019-03-22 20:34 UTC, frommMoritz approved these changes

2019-03-22 20:34 UTC, merged